# Generated by Django 6.0.4 on 2026-05-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_seats',
            field=models.IntegerField(default=1),
        ),
    ]
