# Generated by Django 6.0.4 on 2026-05-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_booking_number_of_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(max_length=100),
        ),
    ]
