services:
  - type: web
    name: quickgo-bus-reservation
    runtime: python
    buildCommand: "./build.sh"
    
    startCommand: "python manage.py migrate && python populate_buses.py && gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DB_ENGINE
        value: "django.db.backends.mysql"
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "4000"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL
        value: "True"
