# Generated by Django 6.0.4 on 2026-04-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='seats',
            new_name='available_seats',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='name',
            new_name='bus_name',
        ),
        migrations.AddField(
            model_name='bus',
            name='total_seats',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
