# Generated by Django 6.0.4 on 2026-05-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_rename_seats_bus_available_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
